name: CI

on:
  push:
    branches:
      - dev
      - prod
      - 274-rewrite-tests
  pull_request:

jobs:
  files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.changed_files.outputs.only_changed == 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v45.0.6
        with:
          files: |
            assets/**
            public/**
            .vscode/**
            .github/**
            !.github/workflows/ci.yml
            **.md
            nodeËmodules/** # the committed node modules folder

  # lint:
  #   needs: files
  #   timeout-minutes: 10
  #   runs-on: ubuntu-latest
  #   name: Lint

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Set Node.js version to 22
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 22

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Build
  #       run: npm run build

  #     - name: Lint
  #       run: npm run lint

  test:
    needs: files
    if: needs.files.outputs.should_skip != 'true'

    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    name: Build & Test

    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [22]
        # node_version: [18, 20, 22]
        # include:
        #   - os: windows-latest
        #     node_version: 22
        #   - os: macos-latest
        #     node_version: 22
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node.js version to ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm run dev &
        env:
          NODE_ENV: development

      # Step 5: Wait for the server to be ready
      - name: Wait for server
        run: |
          echo "Waiting for server to start..."
          until curl -s http://localhost:3000 > /dev/null; do
            echo "Server not ready yet..."
            sleep 5
          done
          echo "Server is up!"

      - name: Test
        run: npm run test
        env:
          NUXT_PUBLIC_BACKEND: http://localhost:3000/api/

      # Step 7: Cleanup server (optional, if not automatically terminated)
      - name: Stop server
        if: always()
        run: kill $(lsof -t -i:3000)
